In [61]:
# Load the Excel file data in sheet number 2 using pandas
import pandas as pd
pd.set_option("display.max_columns", None)

# Load the Excel file data in sheet number 2 using pandas, use the first row as the column names
df = pd.read_excel("Case Study for Data Scientist.xlsx", sheet_name="Sheet1", header=0)
df.head()

categorical_features = df.select_dtypes(include=["object"]).columns
print(categorical_features)
print(len(categorical_features))

numerical_features = df.select_dtypes(include=["int64", "float64"]).columns
# numerical_features = numerical_features.drop('Actual OER %')
print(numerical_features)
print(len(numerical_features))

label = "Actual OER %"

Index(['Day', 'Region', 'Mill Code', 'Mill Type'], dtype='object')
4
Index(['Actual OER %', 'Crop Freshness Score', 'Ripe %', 'Long Stalk %',
       'Rat Damage %', 'Loose Fruits %', 'Rainfall (mm)',
       'Age Profile (years)', 'Total Oil Losses %', 'Downtime %',
       'FFB Processed (MT)', 'Seed A %', 'Seed B %', 'Other Seeds %',
       'Coastal %', 'Inland %'],
      dtype='object')
16

In [62]:
# ZO22 is chosen as the mill code to be analyzed
zo22 = df[df["Mill Code"] == "Z013"]
# set the Date as the index
zo22.head(10)

,Day,Date,Region,Mill Code,Mill Type,Actual OER %,Crop Freshness Score,Ripe %,Long Stalk %,Rat Damage %,Loose Fruits %,Rainfall (mm),Age Profile (years),Total Oil Losses %,Downtime %,FFB Processed (MT),Seed A %,Seed B %,Other Seeds %,Coastal %,Inland %
21192,Wed,2020-01-01,R02,Z013,IP,0.00,300.000000,80.182149,2.766647,7.210191,6.339536,0.000000,9.447821,0.000000,0.000000,0.000,8.390367,0.000000,91.609633,82.195041,17.804959
21193,Thu,2020-01-02,R02,Z013,IP,22.15,281.000465,82.657410,2.847804,7.371022,10.763054,8.032153,9.364802,1.319473,0.024448,446.315,1.071354,0.000000,98.928646,61.805700,38.194300
21194,Fri,2020-01-03,R02,Z013,IP,0.00,285.398388,82.225266,2.522006,5.718668,2.854806,7.736928,11.121556,0.000000,0.000000,0.000,6.001510,0.000000,93.998490,67.253816,32.746184
21195,Sat,2020-01-04,R02,Z013,IP,19.89,282.082143,83.240038,3.270638,7.464708,10.459727,9.509044,11.317018,1.610800,0.054224,468.159,1.697346,0.000000,98.302654,72.430387,27.569613
21196,Sun,2020-01-05,R02,Z013,IP,0.00,270.239774,86.574401,3.548307,7.648801,5.847861,31.419252,11.889726,0.000000,0.000000,0.000,0.000000,0.000000,100.000000,37.864196,62.135804
21197,Mon,2020-01-06,R02,Z013,IP,22.37,289.330459,87.936683,3.066685,6.734878,6.206426,6.916341,12.084396,1.762564,0.147872,347.157,0.476805,2.219019,97.304176,67.845086,32.154914
21198,Tue,2020-01-07,R02,Z013,IP,0.00,285.962145,83.047319,3.017876,2.178759,5.464458,11.648207,10.888256,0.000000,0.000000,0.000,7.885690,2.289306,89.825004,72.194630,27.805370
21199,Wed,2020-01-08,R02,Z013,IP,20.42,275.718290,86.151483,3.995211,7.072296,8.004161,2.475473,11.561366,1.848618,0.037508,440.340,9.140300,2.338331,88.521369,64.895304,35.104696
21200,Thu,2020-01-09,R02,Z013,IP,23.02,289.642535,86.249098,2.717862,6.489738,5.626834,38.731676,11.082954,2.005188,0.049318,370.766,6.766065,2.732541,90.501394,69.776995,30.223005
21201,Fri,2020-01-10,R02,Z013,IP,19.54,288.645099,90.743049,2.270275,5.958360,7.109159,2.130685,10.142015,1.728371,0.198716,342.549,2.057232,1.130730,96.812038,84.255023,15.744977

In [63]:
# From the Date column filter the Data from 2024-12-01 onwards
zo22_df = zo22[zo22["Date"] >= "2024-10-01"]
zo22_df.head(10)
# Remove the categorical columns
zo22_df = zo22_df.drop(columns=categorical_features)
# Remove the null values
zo22_df = zo22_df.dropna()
# Set the date as the index
zo22_df = zo22_df.set_index("Date")

refined_features = numerical_features.drop(["Other Seeds %", "Seed B %", "Inland %"])
# Remove the columns that are not required from zo22_df based on the refined_features
order = [
        "Crop Freshness Score",
        "Ripe %",
        "Long Stalk %",
        "Rat Damage %",
        "Loose Fruits %",
        "Rainfall (mm)",
        "Age Profile (years)",
        "Total Oil Losses %",
        "Downtime %",
        "FFB Processed (MT)",
        "Seed A %",
        "Coastal %",
    ]
zo22_df = zo22_df[order]

In [64]:
zo22_df.head(10)

,Crop Freshness Score,Ripe %,Long Stalk %,Rat Damage %,Loose Fruits %,Rainfall (mm),Age Profile (years),Total Oil Losses %,Downtime %,FFB Processed (MT),Seed A %,Coastal %
Date,,,,,,,,,,,,
2024-10-01,279.131268,84.190405,3.400300,9.355905,2.379274,3.502374,13.918280,1.920196,0.061842,415.135,0.442039,63.688545
2024-10-02,274.492581,86.858343,2.835666,8.690300,7.657143,0.000000,12.816713,1.567388,0.061542,323.768,0.297329,60.322880
2024-10-03,273.968050,85.485258,4.449555,7.284336,6.654633,9.057736,13.730038,1.705754,0.074114,430.537,0.520543,81.585009
2024-10-04,292.344378,81.864123,4.998159,7.411814,4.007937,2.620900,14.174922,1.990100,0.093347,274.172,0.000000,84.962850
2024-10-05,257.116317,83.190953,3.189257,6.539176,10.255205,0.000000,13.257333,1.828140,0.035224,397.970,1.977613,48.191540
2024-10-06,282.315751,84.636922,2.156792,5.286850,13.016386,1.613801,12.677639,0.000000,0.000000,0.000,0.000000,74.890376
2024-10-07,292.050938,84.058713,3.163539,9.169839,22.887316,0.000000,12.936414,1.765013,0.053667,326.485,10.199786,63.445022
2024-10-08,275.952006,87.519040,2.830230,9.398398,8.646274,0.000000,12.295299,1.812159,0.000000,445.934,0.000000,56.423841
2024-10-09,270.274976,86.071483,3.424138,8.711813,7.606980,0.000000,11.720223,2.007313,0.006254,476.998,0.000000,45.078175
2024-10-10,243.171701,86.833068,3.293959,9.054928,8.203926,1.241733,14.772973,2.325589,0.060193,267.845,0.000000,47.228841

In [65]:
# Load the model 
from joblib import load

model = load("zir_trained.pkl")
# Predict the Actual OER % using the model
zo22_df["Predicted OER %"] = model.predict(zo22_df)
zo22_df.head(10)

,Crop Freshness Score,Ripe %,Long Stalk %,Rat Damage %,Loose Fruits %,Rainfall (mm),Age Profile (years),Total Oil Losses %,Downtime %,FFB Processed (MT),Seed A %,Coastal %,Predicted OER %
Date,,,,,,,,,,,,,
2024-10-01,279.131268,84.190405,3.400300,9.355905,2.379274,3.502374,13.918280,1.920196,0.061842,415.135,0.442039,63.688545,21.195856
2024-10-02,274.492581,86.858343,2.835666,8.690300,7.657143,0.000000,12.816713,1.567388,0.061542,323.768,0.297329,60.322880,21.404142
2024-10-03,273.968050,85.485258,4.449555,7.284336,6.654633,9.057736,13.730038,1.705754,0.074114,430.537,0.520543,81.585009,21.051935
2024-10-04,292.344378,81.864123,4.998159,7.411814,4.007937,2.620900,14.174922,1.990100,0.093347,274.172,0.000000,84.962850,20.973480
2024-10-05,257.116317,83.190953,3.189257,6.539176,10.255205,0.000000,13.257333,1.828140,0.035224,397.970,1.977613,48.191540,21.424907
2024-10-06,282.315751,84.636922,2.156792,5.286850,13.016386,1.613801,12.677639,0.000000,0.000000,0.000,0.000000,74.890376,0.000000
2024-10-07,292.050938,84.058713,3.163539,9.169839,22.887316,0.000000,12.936414,1.765013,0.053667,326.485,10.199786,63.445022,21.100330
2024-10-08,275.952006,87.519040,2.830230,9.398398,8.646274,0.000000,12.295299,1.812159,0.000000,445.934,0.000000,56.423841,21.464685
2024-10-09,270.274976,86.071483,3.424138,8.711813,7.606980,0.000000,11.720223,2.007313,0.006254,476.998,0.000000,45.078175,21.630932
2024-10-10,243.171701,86.833068,3.293959,9.054928,8.203926,1.241733,14.772973,2.325589,0.060193,267.845,0.000000,47.228841,21.257130

In [66]:
import warnings
warnings.filterwarnings("ignore")
from scipy.optimize import differential_evolution


# Define the bounds for the features

bounds = [
    (280, zo22["Crop Freshness Score"].max()),  # Crop Freshness Score
    (90, zo22["Ripe %"].max()),  # Ripe %
    (zo22["Long Stalk %"].min(), 5),  # Long Stalk %
    (zo22["Rat Damage %"].min(), 5),  # Rat Damage %
    (8, zo22["Loose Fruits %"].max()),  # Loose Fruits %
    (zo22["Rainfall (mm)"].min(0), 5),  # Rainfall (mm)
    (13.92, 13.92),  # Age Profile (years)
    (1.92, 1.92),  # Total Oil Losses %
    (0.06, 0.06),  # Downtime %
    (0, zo22['FFB Processed (MT)'].max()),  # FFB Processed (MT)
    (0.44, 0.44),  # Seed A %
    (63, 63),  # Coastal %
]
#print(zo22["Crop Freshness Score"].max())
#print(zo22["Ripe %"].max())
#print(zo22["Ripe %"].min())
#print(zo22["Long Stalk %"].min())
#print(zo22["Rat Damage %"].min())
#print(zo22["Loose Fruits %"].max())
#print(zo22["Rainfall (mm)"].min())
#print(zo22["FFB Processed (MT)"].max())


zo22_df_day1 = zo22_df[zo22_df.index == "2024-10-01"]
zo22_df_day1.head()

def obj_fun(X):
    X = [X]
    results = model.predict(X)
    return -results


# Optimize the objective function using differential_evolution
result = differential_evolution(obj_fun, bounds)

# Print the optimized values

print(f"Optimized value for Crop Freshness Score: {result.x[0]}")
print(f"Optimized value for Ripe %: {result.x[1]}")
print(f"Optimized value for Long Stalk %: {result.x[2]}")
print(f"Optimized value for Rat Damage %: {result.x[3]}")
print(f"Optimized value for Loose Fruits %: {result.x[4]}")
print(f"Optimized value for Rainfall (mm): {result.x[5]}")
print(f"Optimized value for Age Profile (years): {result.x[6]}")
print(f"Optimized value for Total Oil Losses %: {result.x[7]}")
print(f"Optimized value for Downtime %: {result.x[8]}")
print(f"Optimized value for FFB Processed (MT): {result.x[9]}")
print(f"Optimized value for Seed A %: {result.x[10]}")
print(f"Optimized value for Coastal %: {result.x[11]}")
print(f"Optimized value for Actual OER %: {-result.fun}")
print(-result.fun)

Optimized value for Crop Freshness Score: 298.48765886764704
Optimized value for Ripe %: 93.51933640213775
Optimized value for Long Stalk %: 0.33074579040080776
Optimized value for Rat Damage %: 0.07423245254114486
Optimized value for Loose Fruits %: 8.567358276624468
Optimized value for Rainfall (mm): 3.4205678844280674
Optimized value for Age Profile (years): 13.92
Optimized value for Total Oil Losses %: 1.92
Optimized value for Downtime %: 0.06
Optimized value for FFB Processed (MT): 86.55347956075991
Optimized value for Seed A %: 0.44
Optimized value for Coastal %: 63.0
Optimized value for Actual OER %: 22.64045059872811
22.64045059872811

In [67]:

# filter 2024-10-01 from the zo22_df
zo22_day1 = zo22[zo22['Date'] == "2024-10-01"]
zo22_day1.head()

,Day,Date,Region,Mill Code,Mill Type,Actual OER %,Crop Freshness Score,Ripe %,Long Stalk %,Rat Damage %,Loose Fruits %,Rainfall (mm),Age Profile (years),Total Oil Losses %,Downtime %,FFB Processed (MT),Seed A %,Seed B %,Other Seeds %,Coastal %,Inland %
22927,Tue,2024-10-01,R02,Z013,IP,20.24,279.131268,84.190405,3.4003,9.355905,2.379274,3.502374,13.91828,1.920196,0.061842,415.135,0.442039,0.0,99.557961,63.688545,36.311455